# Generated by Django 4.2.4 on 2024-01-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0012_agentvodabundleprice_vodabundleprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='afa_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
