# Generated by Django 4.2.4 on 2024-04-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0013_admininfo_afa_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='afaregistration',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='afaregistration',
            name='region',
            field=models.CharField(blank=True, choices=[('Ashanti Region', 'Ashanti Region'), ('Brong-Ahafo Region', 'Brong-Ahafo Region'), ('Central Region', 'Central Region'), ('Eastern Region', 'Eastern Region'), ('Greater Accra Region', 'Greater Accra Region'), ('Northern Region', 'Northern Region'), ('Oti Region', 'Oti Region'), ('Upper East Region', 'Upper East Region'), ('Upper West Region', 'Upper West Region'), ('Volta Region', 'Volta Region'), ('Western Region', 'Western Region'), ('Ahafo Region', 'Ahafo Region'), ('Bono Region', 'Bono Region'), ('Bono East Region', 'Bono East Region'), ('North East Region', 'North East Region'), ('Savannah Region', 'Savannah Region')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='afaregistration',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='afaregistration',
            name='reference',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
