# Generated by Django 4.2.4 on 2025-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0015_agentbigtimebundleprice_bigtimebundleprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afaregistration',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='bigtimetransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='mtntransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='vodafonetransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
    ]
