# Generated by Django 4.2.4 on 2025-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0016_alter_afaregistration_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='agent_registration_fee',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
    ]
